// GUILANG
// ========================================================================= //
/*	This file specifies the first version of GUILANG. The file specifying the
	grammar had better (!!!!) match the expressions specified at the head of
	each of the functions in this file.
	Expressions should be read literally, besides the following types:
	$WORD	References another GUI object generated by a different function.
	WORD*	Kleene star, 0 or more copies of WORD.
	[WORD*]	A list of possible optional terms
	#		Any number.
*/

//Error log
// ========================================================================= //]
// This should never have to be called! Parser should do work correctly!!!!
void
guilang_error
(
	guilang_processor* processor,
	const char* message,
	const char* word
)
{
	char errorstring[LANG_LINELEN]; 
	sprintf(errorstring, message, word);
	errorlog_logdef(processor->log, "GUILANG TRANSLATOR", errorstring);
}

// WINDOW
// ========================================================================= //
// WINDOW[([[x, y, w, h]:#]* )]{ $CELL* }
gui_window*
guilang_buildwindow
(
	guilang_processor* processor
)
{
	if (strcmp(processor->current, "WINDOW") != 0) return NULL;
	float x = 0.0;
	float y = 0.0;
	float w = 1.0;
	float h = 1.0;
	
	guilang_processor_match(processor, "WINDOW");
	char* curr = guilang_processor_consume(processor);
	
	if (curr[0] == '(') {
		float* param;
		do {
			curr = guilang_processor_consume(processor);
			switch(curr[0]) {
				case 'x': param = &x; break;
				case 'y': param = &y; break;
				case 'w': param = &w; break;
				case 'h': param = &h; break;
				default: guilang_error(processor, "Bad parameter! WINDOW object does not accept \'%s\'!", curr);
			}
			guilang_processor_match(processor, ":");
			curr = guilang_processor_consume(processor);
			*param = strtod(curr, NULL);
			curr = guilang_processor_consume(processor);
		} while(curr[0] != ')');
	}
	
	gui_window* gw = gui_window_init(x, y, w, h);
	return gw;
}

// GUI
// ========================================================================= //
// GUI[( [[x, y, w, h]:#]* )]{ $WINDOW* }
gui*
guilang_buildgui
(
	char** stream,
	errorlog* log,
	event_bus* bus
)
{
	float x = 0.0;
	float y = 0.0;
	float w = 1.0;
	float h = 1.0;

	guilang_processor* processor = guilang_processor_init(stream, log, bus);
	
	guilang_processor_match(processor, "GUI");
	
	char* curr = guilang_processor_consume(processor);
	
	if (curr[0] == '(') {
		float* param;
		do {
			curr = guilang_processor_consume(processor);
			switch(curr[0]) {
				case 'x': param = &x; break;
				case 'y': param = &y; break;
				case 'w': param = &w; break;
				case 'h': param = &h; break;
				default: guilang_error(processor, "Bad parameter! GUI object does not accept \'%s\'!", curr);
			}
			guilang_processor_match(processor, ":");
			curr = guilang_processor_consume(processor);
			*param = strtod(curr, NULL);
			curr = guilang_processor_consume(processor);
		} while(curr[0] != ')');
	}
	
	gui* g = gui_init(x, y, w, h);
	gui_window* gw = guilang_buildwindow(processor);
	while(gw != NULL) {
		gui_openwindow(g, gw);
		gw = guilang_buildwindow(processor);
	}
		
	return g;
}